# tokenizer,构造输入

- tokenizer,model:相匹配,tokenzier outputs=>model input
- tokenizer
    - len(input_ids)==len(attention_mask)
    - tokenizer.tokenize(text) 将字符串切分为 token 列表
    - tokenizer.convert_tokens_to_ids(tokens) 将 token 列表转换为 对应的 ID 列表
    - tokenizer.encode(text) 一步完成 tokenize + convert_to_ids，返回 token ID 序列
    - tokenizer(text) 完整的 tokenizer 调用，返回带有 input_ids, attention_mask 等结构的字典

In [15]:
test_senteces=['today is not that bad','today is so bad']
model_name= 'distilbert-base-uncased-finetuned-sst-2-english'

In [16]:
from transformers import AutoTokenizer,AutoModelForSequenceClassification

In [17]:
tokenizer = AutoTokenizer.from_pretrained(model_name)
model=AutoModelForSequenceClassification.from_pretrained(model_name)

In [42]:
batch_input=tokenizer(test_senteces,max_length=256,truncation=True,padding='max_length',return_tensors='pt')
#truncation超过最大长度截取，padding补0，return_tensors 返回pytorch张量

In [41]:
batch_input

{'input_ids': tensor([[ 101, 2651, 2003, 2025, 2008, 2919,  102,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,

In [26]:
tokenizer(test_senteces[0],)

{'input_ids': [101, 2651, 2003, 2025, 2008, 2919, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1]}

In [31]:
tokenizer.encode(test_senteces[0])
## 通常包含：[CLS]、正文、[SEP]

[101, 2651, 2003, 2025, 2008, 2919, 102]

In [29]:
tokenizer.tokenize(test_senteces[0])

['today', 'is', 'not', 'that', 'bad']

In [30]:
tokenizer.convert_tokens_to_ids(tokenizer.tokenize(test_senteces[0]))

[2651, 2003, 2025, 2008, 2919]

In [33]:
tokenizer.decode(tokenizer.encode(test_senteces[0]))#解码器

'[CLS] today is not that bad [SEP]'

In [34]:
tokenizer.vocab

{'trolls': 27980,
 'definitive': 15764,
 '##pipe': 24548,
 '950': 20317,
 'signal': 4742,
 'compensation': 9430,
 'spruce': 19893,
 'jakarta': 14426,
 'spur': 12996,
 'backlash': 25748,
 'semiconductor': 20681,
 'neighbours': 14754,
 'bending': 14457,
 'membrane': 10804,
 '##iko': 12676,
 '[unused711]': 716,
 'demeanor': 21745,
 'dull': 10634,
 '##buro': 23670,
 'dismantled': 17293,
 'psychologist': 15034,
 'bayer': 26367,
 'cattle': 7125,
 'approaches': 8107,
 '##cal': 9289,
 'crane': 11308,
 'stephan': 15963,
 'ს': 1452,
 'interrogation': 16871,
 'ч': 1202,
 'powder': 9898,
 'goalkeeper': 9653,
 'stefan': 8852,
 '##wise': 14244,
 '瀬': 1905,
 'freaked': 22783,
 'adorned': 19189,
 'liza': 20503,
 '##git': 23806,
 'worrying': 15366,
 'ventral': 23420,
 '##inge': 23496,
 'terminating': 23552,
 '##lav': 14973,
 'winkler': 20472,
 'reapers': 27733,
 'nocturnal': 23789,
 '##》': 30166,
 'shuddered': 13937,
 'mythical': 19336,
 'chick': 14556,
 'handheld': 27291,
 'chichester': 23406,
 'cleav

In [35]:
tokenizer.special_tokens_map

{'unk_token': '[UNK]',
 'sep_token': '[SEP]',
 'pad_token': '[PAD]',
 'cls_token': '[CLS]',
 'mask_token': '[MASK]'}

In [45]:
import torch
import torch.nn.functional as F

In [50]:
model.config

DistilBertConfig {
  "activation": "gelu",
  "architectures": [
    "DistilBertForSequenceClassification"
  ],
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "finetuning_task": "sst-2",
  "hidden_dim": 3072,
  "id2label": {
    "0": "NEGATIVE",
    "1": "POSITIVE"
  },
  "initializer_range": 0.02,
  "label2id": {
    "NEGATIVE": 0,
    "POSITIVE": 1
  },
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "output_past": true,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "tie_weights_": true,
  "torch_dtype": "float32",
  "transformers_version": "4.53.2",
  "vocab_size": 30522
}

# model，调用模型

In [52]:
with torch.no_grad():
    outputs=model(**batch_input)
    print(outputs)
    scores=F.softmax(outputs.logits,dim=1)
    print(scores)
    label=torch.argmax(scores,dim=1)# 取概率最高的类别作为预测结果
    print(label)
    res=[model.config.id2label.get(id) for id in label.tolist()]
    print(res)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.4620,  3.6118],
        [ 4.7508, -3.7899]]), hidden_states=None, attentions=None)
tensor([[8.4632e-04, 9.9915e-01],
        [9.9980e-01, 1.9531e-04]])
tensor([1, 0])
['POSITIVE', 'NEGATIVE']


# parse output，输出解析

In [53]:
with torch.no_grad():
    outputs=model(**batch_input)
    print(outputs)
    scores=F.softmax(outputs.logits,dim=1)
    print(scores)
    label=torch.argmax(scores,dim=1)# 取概率最高的类别作为预测结果
    print(label)
    res=[model.config.id2label.get(id) for id in label.tolist()]
    print(res)

SequenceClassifierOutput(loss=None, logits=tensor([[-3.4620,  3.6118],
        [ 4.7508, -3.7899]]), hidden_states=None, attentions=None)
tensor([[8.4632e-04, 9.9915e-01],
        [9.9980e-01, 1.9531e-04]])
tensor([1, 0])
['POSITIVE', 'NEGATIVE']
